import crypto from "node:crypto";
import express from "express";
import PDFDocument from "pdfkit";
import { requireAuth } from "./auth.js";
import { writeReportSummary } from "./gemini.js";
import { findUserById, getHome, getPhoto, listRooms, roomTotals } from "./store.js";

// Builds the claim report PDF for one home, only when the user asks for it.

const EVENTS = { hurricane: "Hurricane", fire: "Fire", "break-in": "Break-in", other: "Other" };
const FOOTER = "Values are estimated replacement costs generated by HomeProof. Not a certified appraisal.";

const C = {
  accent: "#0E6A87",
  accentSoft: "#E7F2F5",
  ink: "#14202B",
  muted: "#56666F",
  line: "#D9E1E6",
  tag: "#E3A33A",
  photoBg: "#EEF2F4",
};

const usd = (n) => "$" + Math.round(n || 0).toLocaleString("en-US");
const longDate = (d) =>
  d.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric", timeZone: "UTC" });
const shortDate = (d) => d.toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric", timeZone: "UTC" });

export const reportRouter = express.Router();

reportRouter.get("/homes/:homeId/report.pdf", requireAuth, async (req, res) => {
  const home = await getHome(req.userId, req.params.homeId);
  if (!home) return res.status(404).json({ error: "Home not found." });

  const rooms = (await listRooms(home._id))
    .filter((r) => r.items.length)
    .map((r) => ({ ...r, total: roomTotals(r).total }));
  if (!rooms.length) {
    return res.status(400).json({ error: "Scan at least one room before making a report." });
  }

  const user = await findUserById(req.userId);
  const event = EVENTS[String(req.query.event || "").toLowerCase()] || null;
  const dateMatch = /^\d{4}-\d{2}-\d{2}$/.test(String(req.query.date || "")) ? new Date(`${req.query.date}T00:00:00Z`) : null;
  const eventDate = dateMatch && !Number.isNaN(dateMatch.getTime()) ? dateMatch : null;

  // Load each item's photo (only this user's photos).
  const photos = new Map();
  for (const item of rooms.flatMap((r) => r.items)) {
    const id = item.photoId && String(item.photoId);
    if (!id || photos.has(id)) continue;
    const photo = await getPhoto(id);
    if (photo && String(photo.userId) === String(req.userId)) photos.set(id, photo.data);
  }

  const summary = await writeReportSummary({ homeName: home.name, event, rooms });
  const now = new Date();
  const reportId = `HP-${now.toISOString().slice(0, 10).replace(/-/g, "")}-${crypto.randomBytes(2).toString("hex").toUpperCase()}`;

  const pdf = buildPdf({ user, home, rooms, photos, event, eventDate, summary, reportId, generatedAt: now });
  const slug = home.name.replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "") || "Home";
  res.set("Content-Type", "application/pdf");
  res.set("Content-Disposition", `inline; filename="HomeProof-Claim-Report-${slug}.pdf"`);
  res.set("X-Report-Id", reportId);
  pdf.pipe(res);
  pdf.end();
});

function buildPdf({ user, home, rooms, photos, event, eventDate, summary, reportId, generatedAt }) {
  const doc = new PDFDocument({
    size: "LETTER",
    margins: { top: 50, bottom: 64, left: 50, right: 50 },
    bufferPages: true, // lets us write "Page X of Y" at the end
    info: { Title: `HomeProof Claim Report – ${home.name}`, Author: "HomeProof" },
  });
  const left = doc.page.margins.left;
  const width = doc.page.width - left - doc.page.margins.right;
  const bottom = () => doc.page.height - doc.page.margins.bottom;
  const ensureSpace = (h) => {
    if (doc.y + h > bottom()) doc.addPage();
  };

  const items = rooms.flatMap((r) => r.items);
  const grandTotal = rooms.reduce((s, r) => s + r.total, 0);

  // ---- header ----
  drawLogo(doc, left, 46);
  doc.font("Helvetica-Bold").fontSize(18).fillColor(C.ink).text("HomeProof", left + 36, 50);
  doc.font("Helvetica").fontSize(9).fillColor(C.muted).text("Home inventory for insurance", left + 36, 70);
  doc.fontSize(9).fillColor(C.muted).text(`Report ID  ${reportId}`, left, 52, { width, align: "right" });
  doc.text(`Generated  ${longDate(generatedAt)}`, left, 65, { width, align: "right" });
  doc.moveTo(left, 96).lineTo(left + width, 96).lineWidth(1).strokeColor(C.line).stroke();

  doc.font("Helvetica-Bold").fontSize(22).fillColor(C.ink).text("Home Inventory Claim Report", left, 114);

  // ---- who / where / what ----
  const colW = (width - 24) / 3;
  const infoY = doc.y + 12;
  const info = [
    ["PREPARED FOR", user?.name || "—", user?.email || ""],
    ["PROPERTY", home.name, home.address || "No address given"],
    ["EVENT", event || "Not specified", eventDate ? longDate(eventDate) : "Date not given"],
  ];
  let infoBottom = infoY;
  info.forEach(([label, main, sub], i) => {
    const x = left + i * (colW + 12);
    doc.font("Helvetica-Bold").fontSize(8).fillColor(C.muted).text(label, x, infoY, { width: colW, characterSpacing: 0.6 });
    doc.font("Helvetica-Bold").fontSize(11).fillColor(C.ink).text(main, x, infoY + 14, { width: colW });
    doc.font("Helvetica").fontSize(9.5).fillColor(C.muted).text(sub, { width: colW });
    infoBottom = Math.max(infoBottom, doc.y);
  });

  // ---- total + summary ----
  let y = infoBottom + 18;
  const summaryH = doc.font("Helvetica").fontSize(10.5).heightOfString(summary, { width: width - 32, lineGap: 2 });
  const boxH = 74 + summaryH;
  doc.roundedRect(left, y, width, boxH, 8).fill(C.accentSoft);
  doc.font("Helvetica-Bold").fontSize(8).fillColor(C.accent).text("TOTAL ESTIMATED REPLACEMENT VALUE", left + 16, y + 14, { characterSpacing: 0.6 });
  doc.font("Helvetica-Bold").fontSize(26).fillColor(C.ink).text(usd(grandTotal), left + 16, y + 26);
  doc.font("Helvetica").fontSize(10).fillColor(C.muted).text(
    `${items.length} item${items.length === 1 ? "" : "s"} · ${rooms.length} room${rooms.length === 1 ? "" : "s"}`,
    left + 16, y + 34, { width: width - 32, align: "right" }
  );
  doc.font("Helvetica").fontSize(10.5).fillColor(C.ink).text(summary, left + 16, y + 62, { width: width - 32, lineGap: 2 });
  doc.y = y + boxH + 22;

  // ---- items, grouped by room ----
  const ROW_H = 62;
  const PHOTO_W = 72;
  const PHOTO_H = 54;
  const valueW = 110;

  for (const room of rooms) {
    ensureSpace(34 + ROW_H * Math.min(2, room.items.length));
    y = doc.y;
    doc.font("Helvetica-Bold").fontSize(13).fillColor(C.ink).text(room.name, left, y);
    // Rooms whose last recording passed the location check (made within the home's radius).
    const verified = room.locationProof?.verifiedAt ? ` · Location verified ${shortDate(new Date(room.locationProof.verifiedAt))}` : "";
    doc.font("Helvetica").fontSize(9.5).fillColor(C.muted)
      .text(`${room.items.length} item${room.items.length === 1 ? "" : "s"}${verified}`, left, y + 3, { width, align: "right" });
    doc.moveTo(left, y + 20).lineTo(left + width, y + 20).lineWidth(1.5).strokeColor(C.accent).stroke();
    doc.y = y + 28;

    for (const item of room.items) {
      ensureSpace(ROW_H);
      y = doc.y;
      drawPhoto(doc, photos.get(String(item.photoId)), item.box, left, y, PHOTO_W, PHOTO_H);
      if (item.timestamp) {
        doc.roundedRect(left + 3, y + PHOTO_H - 14, 30, 11, 2).fill(C.tag);
        doc.font("Helvetica-Bold").fontSize(7).fillColor("#3A2606").text(item.timestamp, left + 3, y + PHOTO_H - 12, { width: 30, align: "center" });
      }

      const textX = left + PHOTO_W + 12;
      const textW = width - PHOTO_W - 12 - valueW - 8;
      const serial = item.serialNumber?.trim();
      // With a serial number the name gets one line, so everything fits in the row.
      doc.font("Helvetica-Bold").fontSize(11).fillColor(C.ink)
        .text(item.name, textX, y + 6, { width: textW, height: serial ? 14 : 28, ellipsis: true });
      const meta = [
        item.category,
        cap(item.condition),
        item.editedByUser && "Edited by owner",
        item.addedAt && `Added ${shortDate(new Date(item.addedAt))}`, // came from a later "add items" clip
      ].filter(Boolean).join(" · ");
      doc.font("Helvetica").fontSize(9.5).fillColor(C.muted).text(meta, textX, doc.y + 2, { width: textW, height: 12, ellipsis: true });
      if (serial) {
        doc.font("Helvetica").fontSize(9).fillColor(C.muted).text("Serial no. ", textX, doc.y + 2, { continued: true });
        doc.font("Courier-Bold").fontSize(9).fillColor(C.ink).text(serial, { width: textW, lineBreak: false });
      }

      doc.font("Helvetica-Bold").fontSize(12).fillColor(C.ink).text(usd(item.estValue), left + width - valueW, y + 6, { width: valueW, align: "right" });
      doc.font("Helvetica").fontSize(9).fillColor(C.muted)
        .text(`Range ${usd(item.estLow)}–${usd(item.estHigh)}`, left + width - valueW, y + 24, { width: valueW, align: "right" });

      doc.moveTo(textX, y + ROW_H - 4).lineTo(left + width, y + ROW_H - 4).lineWidth(0.5).strokeColor(C.line).stroke();
      doc.y = y + ROW_H;
    }

    ensureSpace(30);
    y = doc.y + 2;
    doc.font("Helvetica-Bold").fontSize(10.5).fillColor(C.muted).text(`${room.name} subtotal`, left, y, { width: width - valueW });
    doc.fillColor(C.ink).text(usd(room.total), left + width - valueW, y, { width: valueW, align: "right" });
    doc.y = y + 30;
  }

  // ---- grand total ----
  ensureSpace(70);
  y = doc.y + 4;
  doc.roundedRect(left, y, width, 52, 8).fill(C.accent);
  doc.font("Helvetica-Bold").fontSize(12).fillColor("#FFFFFF").text("Grand total (estimated)", left + 16, y + 19);
  doc.fontSize(20).text(usd(grandTotal), left + 16, y + 14, { width: width - 32, align: "right" });
  doc.y = y + 64;
  doc.font("Helvetica").fontSize(9).fillColor(C.muted).text(
    "Each value is an estimate of what it would cost to replace the item today with a similar one, based on photos " +
      "taken by the owner. Items marked \"Edited by owner\" were corrected by the owner after the scan.",
    left, doc.y, { width }
  );

  // ---- footer on every page ----
  const range = doc.bufferedPageRange();
  for (let i = 0; i < range.count; i++) {
    doc.switchToPage(range.start + i);
    const savedBottom = doc.page.margins.bottom;
    doc.page.margins.bottom = 0; // writing inside the margin must not create a new page
    const fy = doc.page.height - 42;
    doc.moveTo(left, fy - 8).lineTo(left + width, fy - 8).lineWidth(0.5).strokeColor(C.line).stroke();
    doc.font("Helvetica").fontSize(8).fillColor(C.muted).text(FOOTER, left, fy, { width: width - 80, lineBreak: false });
    doc.text(`Page ${i + 1} of ${range.count}`, left + width - 80, fy, { width: 80, align: "right", lineBreak: false });
    doc.page.margins.bottom = savedBottom;
  }
  return doc;
}

const cap = (s) => (s ? s[0].toUpperCase() + s.slice(1) : "");

// The item photo, zoomed in on the item when Gemini gave its position
// (box = [ymin, xmin, ymax, xmax], 0–1000). A grey box if there is no photo.
function drawPhoto(doc, data, box, x, y, w, h) {
  doc.save();
  doc.roundedRect(x, y, w, h, 5).clip();
  doc.rect(x, y, w, h).fill(C.photoBg);
  if (data) {
    try {
      if (box?.length === 4) {
        const img = doc.openImage(data);
        const r = regionAround(box, img.width, img.height, w / h);
        const scale = w / r.width;
        doc.image(img, x - r.x * scale, y - r.y * scale, { width: img.width * scale });
      } else {
        doc.image(data, x, y, { cover: [w, h], align: "center", valign: "center" });
      }
    } catch {
      /* unreadable image: keep the grey box */
    }
  }
  doc.restore();
}

// The part of the photo (with the cell's aspect ratio) centred on the item, with some margin.
function regionAround(box, imgW, imgH, aspect, padding = 1.25) {
  const [y1, x1, y2, x2] = box.map((n) => n / 1000);
  let width = Math.max((x2 - x1) * imgW, (y2 - y1) * imgH * aspect, Math.min(imgW, imgH) * 0.3) * padding;
  width = Math.min(width, imgW, imgH * aspect); // can't be bigger than the photo
  const height = width / aspect;
  const clamp = (v, max) => Math.min(Math.max(v, 0), max);
  return {
    x: clamp(((x1 + x2) / 2) * imgW - width / 2, imgW - width),
    y: clamp(((y1 + y2) / 2) * imgH - height / 2, imgH - height),
    width,
  };
}

// Simple HomeProof mark: teal rounded square with a white house outline and a check.
function drawLogo(doc, x, y) {
  doc.roundedRect(x, y, 28, 28, 7).fill(C.accent);
  doc.save();
  doc.lineWidth(2).strokeColor("#FFFFFF").lineJoin("round").lineCap("round");
  doc.moveTo(x + 7, y + 13).lineTo(x + 14, y + 7).lineTo(x + 21, y + 13).lineTo(x + 21, y + 21).lineTo(x + 7, y + 21).closePath().stroke();
  doc.strokeColor(C.tag).moveTo(x + 10.5, y + 16).lineTo(x + 13, y + 18.5).lineTo(x + 17.5, y + 14).stroke();
  doc.restore();
}
